language: generic
sudo: required
dist: trusty
env:
  global:
  - OWNER='EA31337'
  - EA_MODE='Lite'
  - EA_VERSION='v1.67'
  - USER=${TRAVIS_REPO_SLUG%%/*}
  - REPOSITORY=${TRAVIS_REPO_SLUG##*/}
  - PUSH_BRANCH="EA-$(date +%Y%m%d)"
  - CWD="$TRAVIS_BUILD_DIR"
  - VM_DIR="$CWD/_VM"
  - EA_DIR="$VM_DIR/EA"
  - PATH="$PATH:$CWD/_scripts:$CWD/_VM/scripts"
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
# - secure: crXsd5puGxZaDE9EVTDLU0tMeH3JRmIAUwLhBjheBPzbzT/buE1owFsaeGsr/XQStNrt2EWq8LxN/c4TOkHJ9tTU8f6+3IUkAXvzqYwwcE+HbY3KJ4jJd2KHRQ5NbwpAkDtADvcrw5CDdWGmMiOEaA54l4GCBg0Id5jWOy2KbKXBnjWeaZu6irYT1B6HMAYSxPKWVHriku323tgH3FgAn1HtKK2nhOPjulBj6vj/ioS7xy20sz9j2yN7hExGB1k0GGUSNi7O74xYqLHhBJISp7LplHbaTJCMi5/xd9h9kSfsTLxJtXTqxat/92JburhzFvGBEjd4gJOiZxJw0vymTVJaqwpfy7joD3QD6jz/nF7w5HSnTvEly6wLCOH00TbrfPvwPvFvfXTFl6diNZEfZCwiSJa9eM88hDkpPyp8+O2w9TprASI66qmsM2z3vt2UM4L5k5QfYrIVPE9J4LE1btjX4cecQVb1oauE5N9Hr77e92R5lfA7LgAcT5TluG5AMNJSEbDmdYrnz9W+nlm+2ML3OhdfWHvcvMFSI0Cjpn+9ZF88pGFBc0qjiQQPJCq7WwBgC3pMYsuioV92BNevCDtzCEPL4hp/oc69K+tKxzb4/OdFWSJO5zEKOno1FCheFHLTNl7qbDUt/5xz08hSwtWf7aR5da1CT7eG4RVJCoY=
# - secure: eMGIXPSYLk1LIxqocS3CuHl+vxUSr1ZDs38yNdA6jwc/7zeWn7zA0+N2zHKr9UzkHDYJ9cbLDlJZk/M8umtDr3H3orld3TCSXMgtyKqCdDV3T4rwmcJs3InyrOa7Ia72FNJttjpToQ53oWnMqCk/eN7sLL4ZJLmJxAlkW5JK5fml0UYn03jrE3ggXmjjm/CpjrkurgfioDL7xhxtnACHCNuWRupXxI4486rzAW6enqrluVcr25a0Zn7ZAAseIxqQhEuUqiyJlKRcrlaO3yDYIa1AI0drLYMlmOcEAxcSzVIwTX79CV4C7UQWg2SHYOXYK+ak+AXwKvr8Q4y5u4PZBvBZTOELHRW61MvDq5NjAvvEgc5VvHtsWG7b0Qqe0N3EU4cJBqLfeOettFd4rA+VBRgUVoUXaXgQlKibKBG4kBEM030mIfLzTMAAYduYNiallzffGhn4ZRzTQPOAM298sh5moIo5yIl+1z2bxEXXz0BOs273JZNhBBXzS1CSQoeHZEVvETnnWAUvnNPrZ6moQ6/gkabhyV1jUNiplxGoJ9bSShPzwh1rfgskAyHBrvGiNLnRzU5bx0YJRqT7njqRhPCXfVEa7Q5qWtrXwWF/DNDd9gbeocedsHAsmzlLgfeJsJiVX+9jM7w0/NlHowjhPnBZJYq2dLSzzku6/5Vv/WA=
  - secure: FIsYONUWQC6HaVNat3HP5ih+PwmmhN/o+/4zkshzUPa6Ix5s3EA+l0k4AQLeNta26TkWy4owkrxn2OzSi+No7dDMNNHauSif+RuQaAgrwQTTv7Q0Oa4ElkYE9R2nr2xBRl195L4u+/ln9/24+1p2LtuKY38+pzeGn9+OFZRj7ra+FbpHax0ozwnYK/eNnTwRAwurCUQ7rhlc78Ek3LRl7keMeoinWW9/gZmOYUXh3lC9agnB9gJqZW0ZTgzjwVz3n8b0JqTOc/yPxJVsRgnJ2E0QbRPeXG9tbKgW5n8/JMiaJboD2i1OXE19y8KIDmtQDC+Tejp3SuNSXbB2qiR62RP7nTtvEt2ak2HSPCmEBwWoDsY54vFqOcVh7xw23NLaGoXv1gCh+N2eH1786kL2rcKpYBWh5LsZEUyRCzLT8pI5JLM9m/SxogmExJoI+p6MArAZ+i1rhd2THhOd6BP3jnLTxIoqQxxry5i639SBDzn9CTtzxdoeMQyhzmRkGiVHyxyz5tDSegpSzKGhrYVtWxC2zaa/3WgCiGfamIRFO7cbNsfO6s6VZQc2xIEysv0X1yZDTvjq+BeLAU14Vt+bG1RPomjMPaoDa9n4J7FPDJfRS70Whqr0dO/HSUsYHKlMFcQ9QzkJPA7LKTLNiYkxD48K0hlSimfdmqeT3AY7hdc=
  matrix:
  - PLATFORM=MT4
addons:
  hosts:
  - travis.local
branches:
  only:
  - master
  - dev
  - ci
matrix:
  fast_finish: true
cache:
  apt: true
  pip: true
  directories:
  - "$HOME/.wine"
notifications:
  email: true
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2c50114866dd0ba72f48
    on_success: change
    on_failure: always
    on_start: never
before_install:
- set -e
- git config --local include.path "$CWD/.gitconfig"
- ssh-keyscan -H github.com >> ~/.ssh/known_hosts
install:
- sudo env PATH="$PATH" provision.sh
- sudo env PATH="$PATH" secur32_fix.sh
- mkdir -vp "$EA_DIR"
before_script:
- get_gh_asset.sh EA31337 EA31337-Lite-Releases v1.67 EA31337-Lite-Backtest

- echo "GITHUB_API_TOKEN=$GITHUB_API_TOKEN" > ~/.secrets
- (cd "$EA_DIR"; get_gh_asset.sh $OWNER $OWNER-$EA_MODE-Releases $EA_VERSION Backtest) || exit 0
# |-
# if [ -n "$PS" ]; then
#   eval "$(ssh-agent -s)"
#   install -vm700 <(echo "echo $PS") $HOME/.ps
#   git config --get key.travis | tr '|' '\n' | rev | base64 -d | gunzip -c | DISPLAY= SSH_ASKPASS=$HOME/.ps ssh-add -
#   ssh-add -l
# else # Otherwise run sample EA.
#   run_backtest.sh
#   exit 0
# fi
script:
- find "$CWD" -name "*.rules" -exec bash -n "{}" ';'
- run_main_backtest.sh
after_success:
- echo "Success."
after_failure:
- tree -dL 3 ~/
- find ~/.wine -name "*.log" -print -execdir tail "{}" ';'
after_script:
- pwd
deploy:
  provider: releases
  api_key:
    secure: loTZKrdYEptxw6zgPqL3mJ3XrC7Kh71QQI9qKxMgC5C6IDwYRHZ1PSx8T87r2B+Kg/iRlim9XStu7c8Rg3A0Tm79Y7SeTALZEIYdL2frakkln1r1tiKjGmSgenIoFqaTpGTcMH+rK3NibuhL7Jlw/MkatA+JyrPCvnp/JNNCgxFuc1xkqFW6PGsCP+fil1HhSf4kbIqSZSzW2uhzFGapZsXigxM/6BwNa7D/VF9Gk6AWGR3FTFWXUKPbWqaYiP58uxZv6842hgbXs7VKXHNPr0P1rzIZLbSBQzcPZAKs6CiON/XEu2Ao0NSJQMAKtP5bVJtZIMpUJFDAk/3Y1mSyvYsEbDYIyZIbVY1d7hHAsqDevlpXUUm4/iGr3aLsnBQPEGDSBS/CfvgHnfuZipRyk1p0+4HitBiIu84gtovhIKw/YQhx/I73HSNvqDbCpC+CqrViXoRFNxaVGM2CcsULS/GkBuwMbHYvWIsjMe0PLSHFXMTc76awOKXb9+GyTz5IhKxgJZ5+yYwN4gFe+EHpRMW9HRbagGAVqLRzdVX8HmlBLR7AxlqGwPiRk8auVOMgUGaE2TZy+KUdloq+5Lwc/2EdALxlQ/kAEju82MnYNDrsPtHCzQcHZUR2PeWYW0Y94wIoS/igSPdooVxN9/qKLAI0zJs1gfdkDhbZ8pSZN5s=
  file:
  - EURUSD-2000USD-10spread/EURUSD-2000USD-2014year-10spread-DS-main-test.txt
  - EURUSD-2000USD-10spread/EURUSD-2000USD-2014year-10spread-DS-main-test.gif
  on:
    repo: EA31337/EA31337-Lite-Sets
    tags: true
